# Generated by Django 4.0.2 on 2022-03-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='survivorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Unsure')], max_length=4)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('infected', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')])),
            ],
        ),
        migrations.DeleteModel(
            name='survivor_model',
        ),
    ]
